export default {
  icon: "De",
  by: "von",
  DataNotAvailable: "Keine Daten empfangen!",
  AppCreator: "Diese App wurde von Iman Bajalan erstellt.",
  TranslationTest: "Dies ist ein Test für die Übersetzungsoption",
  Language: "Sprache",
  Description: "Beschreibung",
  Station: "Station",
  Equipment: "Ausrüstung",
  Home: "Home",
  About: "Um",
  Login: "Anmeldung",
  Signin: "anmelden",
  Help: "Helfen",
  pollutingGasesOne:
    "Die folgenden Diagramme bieten Prognosen für verschiedene Schadstoffgase für die kommenden vier Tage und geben deren Werte stündlich an. Zu diesen Gasen gehören mehrere bedeutende Schadstoffe (alle Werte basieren auf μg/m3), nämlich Kohlenmonoxid (CO), Stickstoffmonoxid (NO), Stickstoffdioxid (NO2), Ozon (O3), Schwefeldioxid (SO2), Ammoniak (NH3) sowie Feinstaub (PM2.5 und PM10).",
  pollutingGasesTwo: `Jedes dieser Gase ist aufgrund seiner potenziellen Auswirkungen auf die Umwelt und die Gesundheit von Bedeutung. Kohlenmonoxid (CO) ist beispielsweise ein farb- und geruchloses Gas, das bei der unvollständigen Verbrennung kohlenstoffhaltiger Brennstoffe entsteht und beim Einatmen insbesondere in geschlossenen Räumen ein Gesundheitsrisiko darstellt. Stickoxide (NO und NO2) tragen zur Luftverschmutzung bei und können verschiedene Probleme verursachen. Ozon (O3) in Bodennähe ist ein wesentlicher Bestandteil von Smog. Schwefeldioxidemissionen (SO2) stammen hauptsächlich aus industriellen Prozessen und können zu saurem Regen beitragen. Ammoniak (NH3) ist eine Verbindung, die häufig in der Landwirtschaft vorkommt und die Luft- und Wasserqualität beeinträchtigen kann. Feinstaub wie PM2,5 und PM10 bezieht sich auf winzige Partikel, die in der Luft schweben.`,
  pollutingGasesThree: `Durch die Überwachung und Prognose der Konzentrationen dieser Schadstoffe im Laufe der Zeit können Einzelpersonen, Gemeinden und Behörden proaktive Maßnahmen ergreifen, um ihre Auswirkungen auf die Umwelt zu mildern. Das Verständnis der Prognosen für diese Gase liefert wertvolle Erkenntnisse für fundierte Entscheidungen, die Umsetzung geeigneter Vorschriften und die Einführung von Maßnahmen zur Reduzierung der Schadstoffbelastung.`,
  pollutingGasesForecast: "Prognose für die nächsten vier Tage.",
  WelcomeText: "Willkommen bei Ihrem meteorologischen Datenzentrum!",
  InfoHomePage:
    "Entdecken Sie meteorologische Echtzeitdaten, die von verschiedenen Stationen in ganz Brandenburg gesammelt wurden. Diese Online-Anwendung sammelt und präsentiert umfassende Wetterinformationen und liefert wertvolle Erkenntnisse für Meteorologen, Forscher und Wetterbegeisterte gleichermaßen.",
  KeyFeatures: "Hauptmerkmale",
  AppFeaturOne:
    "Greifen Sie auf aktuelle Wetterberichte von mehreren Wetterstationen in verschiedenen Regionen zu.",
  AppFeaturTwo:
    "Tauchen Sie ein in detaillierte Grafiken, Diagramme und Karten, die Temperaturtrends, Niederschlagsmengen, Windgeschwindigkeit und mehr darstellen.",
  AppFeaturThree:
    "Verschaffen Sie sich einen umfassenden Überblick über die Daten jeder Station, einschließlich historischer Aufzeichnungen und aktueller Bedingungen.",
  AppFeaturFour:
    "Ganz gleich, ob Sie Wettermuster verfolgen, Klimaveränderungen untersuchen oder sich einfach über die örtlichen Bedingungen auf dem Laufenden halten möchten: Diese Anwendung ist Ihre Anlaufstelle für zuverlässige meteorologische Daten.",
  temperatureForecasts:
    "Temperaturvorhersagen sind für Waldbewirtschaftung und Naturschutzbemühungen von entscheidender Bedeutung. Sie liefern wichtige Informationen für die Vorhersage von Brandrisiken, das Verständnis der Ökosystemdynamik und die Planung der Ressourcenverteilung. Höchst- und Tiefsttemperaturvorhersagen sind besonders wichtig, da sie verschiedene Aspekte der Waldgesundheit und Widerstandsfähigkeit beeinflussen. Extreme Temperaturen können Pflanzen- und Tierarten belasten oder sogar töten, die Bodenfeuchtigkeit beeinträchtigen und die Gefahr von Waldbränden erhöhen. Durch die genaue Vorhersage von Temperaturschwankungen können Forstverwalter Maßnahmen ergreifen, um potenzielle Auswirkungen abzumildern, wie z. B. vorgeschriebene Verbrennungen oder die Anpassung von Bewässerungsplänen. Darüber hinaus hilft das Verständnis von Temperaturmustern bei der Vorhersage von Veränderungen in Lebensraumbereichen und phänologischen Ereignissen und trägt so zur Erhaltung der Artenvielfalt in Waldökosystemen bei.",
  humidityForecasts:
    "Feuchtigkeitsvorhersagen sind auch für die Waldbewirtschaftung und -erhaltung unverzichtbar und bieten unschätzbare Einblicke in das komplexe Feuchtigkeitsgleichgewicht, das für die Gesundheit des Ökosystems entscheidend ist. Sie helfen bei der Vorhersage der Anfälligkeit von Wäldern für Dürrestress, Schädlingsbefall und Krankheitsepidemien, da der Feuchtigkeitsgehalt die Widerstandsfähigkeit der Pflanzen und die mikrobielle Aktivität stark beeinflusst. Hohe Luftfeuchtigkeit fördert die Vermehrung von Pilzen und Krankheitserregern und stellt ein Risiko für die Gesundheit der Bäume dar, während niedrige Luftfeuchtigkeit die Anfälligkeit der Wälder für die Entstehung und Ausbreitung von Waldbränden erhöht. Darüber hinaus tragen Feuchtigkeitsprognosen zur Beurteilung der Luftqualität bei, da eine erhöhte Luftfeuchtigkeit die Bildung von bodennahem Ozon und Feinstaub verstärken kann. Die Integration von Feuchtigkeitsvorhersagen in Waldbewirtschaftungsstrategien ermöglicht proaktive Maßnahmen zur Aufrechterhaltung der Widerstandsfähigkeit des Ökosystems, zum Schutz der biologischen Vielfalt und zur Abmilderung der Auswirkungen von Umweltstressoren auf Waldökosysteme.",
  pressureForecasts:
    "Druckvorhersagen sind für das Verständnis der atmosphärischen Bedingungen, die sich auf Waldökosysteme auswirken, von wesentlicher Bedeutung. Änderungen des Luftdrucks beeinflussen Wettermuster, einschließlich der Bewegung von Luftmassen, der Entstehung von Stürmen und der Niederschlagsverteilung. Schwankungen des Luftdrucks können auf bevorstehende Wettersysteme wie Fronten oder Tiefdruckgebiete hinweisen, die starke Regenfälle, starke Winde oder andere extreme Wetterereignisse mit sich bringen können, die sich auf die Waldgesundheit und die Bewirtschaftungspraktiken auswirken können. Die Überwachung von Druckvorhersagen hilft Forstmanagern, potenzielle Gefahren wie schwere Stürme oder schnelle Wetteränderungen vorherzusehen, und ermöglicht so rechtzeitige Vorbereitungen und Reaktionsmaßnahmen zum Schutz der Wälder und zur Minderung von Risiken für die Artenvielfalt, die Infrastruktur und die öffentliche Sicherheit. Darüber hinaus tragen Druckvorhersagen zum Verständnis umfassenderer Klimatrends und -muster bei und unterstützen die langfristige Planung und Anpassungsstrategien für den Waldschutz und die Waldbewirtschaftung.",
  windSpeed:
    "Windgeschwindigkeitsvorhersagen sind ein wesentlicher Bestandteil effektiver Waldbewirtschaftungs- und Schutzbemühungen und liefern wichtige Informationen über atmosphärische Bedingungen, die das Brandverhalten, die Samenausbreitung und die Baumstabilität beeinflussen. Hohe Windgeschwindigkeiten können die Ausbreitung von Waldbränden beschleunigen, ihre Eindämmung und Löschung erschweren und gleichzeitig die Sicherheit der Feuerwehrleute gefährden. Darüber hinaus kann starker Wind die Wahrscheinlichkeit erhöhen, dass Bäume beschädigt oder entwurzelt werden, was zu potenziellen Gefahren wie herabfallenden Trümmern oder Bäumen führen kann. Umgekehrt können niedrige Windgeschwindigkeiten die Verbreitung von Pollen, Samen und Sporen beeinträchtigen, die für die Regeneration des Waldes und die Artenvielfalt wichtig sind. Durch die Einbeziehung von Windgeschwindigkeitsprognosen in Waldbewirtschaftungsstrategien können Interessenvertreter proaktiv die Verhinderung und Reaktion von Waldbränden planen, Risiken für die Waldinfrastruktur bewerten und forstwirtschaftliche Praktiken optimieren, um die Widerstandsfähigkeit des Ökosystems angesichts sich ändernder Windbedingungen zu verbessern.",
  weatherInsights:
    "Bleiben Sie in Verbindung mit Echtzeit-Wettereinblicken, die speziell auf die Forstwirtschaft zugeschnitten sind. Überwachen Sie wichtige Faktoren wie Luftfeuchtigkeit, Temperatur, Windgeschwindigkeit und Luftdruck, um Strategien zur Waldbewirtschaftung zu optimieren. Ganz gleich, ob es darum geht, das Risiko von Waldbränden einzuschätzen, Holzernteeinsätze zu planen oder die Artenvielfalt zu schützen: Wenn Sie aktuelle Wetterdaten zur Hand haben, können Sie fundierte Entscheidungen treffen. Bleiben Sie potenziellen Bedrohungen immer einen Schritt voraus und maximieren Sie die Gesundheit und Widerstandsfähigkeit Ihres Waldökosystems mit genauen und aktuellen Wetterinformationen. Bleiben Sie auf dem Laufenden über Live-Updates, um sicherzustellen, dass Ihre forstwirtschaftlichen Bemühungen durch die neuesten meteorologischen Erkenntnisse unterstützt werden.",
  onlineInformation:
    "Im Folgenden werden Online-Informationen zu einigen Klimadaten in ",
};
